export const savedWorkout = {
  userId: '4054a73232db7de8',
  id: 21,
  date: '2017-06-24',
  notes: 'bla',
  exercises: [
    {
      id: 92,
      name: 'Bench Press',
      reps: 8,
      sets: 1,
      weight: 88,
      tempo: '101',
      rest: 0,
      workoutOrder: 1,
      superSetIndex: 1
    }, {
      id: 93,
      name: 'Bent Over Barbell Rows',
      reps: 8,
      sets: 1,
      weight: 88,
      tempo: '101',
      rest: 60,
      workoutOrder: 2,
      superSetIndex: 2
    }, {
      id: 100,
      name: 'Incline Barbell Bench Press',
      reps: 8,
      sets: 1,
      weight: 66,
      tempo: '101',
      rest: 60,
      workoutOrder: 3
    }, {
      id: 101,
      name: 'Incline Barbell Bench Press',
      reps: 6,
      sets: 1,
      weight: 66,
      tempo: '101',
      rest: 60,
      workoutOrder: 4
    }
  ]
};

export const allWorkouts = [
  {
    userId: '4054a73232db7de8',
    id: 22,
    date: '2017-06-28',
    notes: '5x5s',
    exercises: [
      {
        id: 109,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 1
      }, {
        id: 110,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 2
      }, {
        id: 111,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 3
      }, {
        id: 112,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 4
      }, {
        id: 113,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 5
      }, {
        id: 114,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 6
      }, {
        id: 115,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 116,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 117,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 118,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 119,
        name: 'Squats',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 11
      }, {
        id: 120,
        name: 'Squats',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 12
      }, {
        id: 121,
        name: 'Squats',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 13
      }, {
        id: 122,
        name: 'Squats',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 14
      }, {
        id: 123,
        name: 'Squats',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 15
      }, {
        id: 124,
        name: 'Power cleans',
        reps: 3,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 16
      }, {
        id: 125,
        name: 'Power cleans',
        reps: 3,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 17
      }, {
        id: 126,
        name: 'Power clean and press',
        reps: 3,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 18
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 21,
    date: '2017-06-24',
    notes: '',
    exercises: [
      {
        id: 92,
        name: 'Bench Press',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 0,
        workoutOrder: 1,
        superSetIndex: 1
      }, {
        id: 93,
        name: 'Bent Over Barbell Rows',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 2,
        superSetIndex: 2
      }, {
        id: 94,
        name: 'Bench Press',
        reps: 6,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 3,
        superSetIndex: 1
      }, {
        id: 95,
        name: 'Bent Over Barbell Rows',
        reps: 6,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 4,
        superSetIndex: 2
      }, {
        id: 96,
        name: 'Bench Press',
        reps: 7,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 5,
        superSetIndex: 1
      }, {
        id: 97,
        name: 'Bent Over Barbell Rows',
        reps: 7,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 6,
        superSetIndex: 2
      }, {
        id: 98,
        name: 'Bench Press',
        reps: 6,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 7,
        superSetIndex: 1
      }, {
        id: 99,
        name: 'Bent Over Barbell Rows',
        reps: 6,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 8,
        superSetIndex: 2
      }, {
        id: 100,
        name: 'Incline Barbell Bench Press',
        reps: 8,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 101,
        name: 'Incline Barbell Bench Press',
        reps: 6,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 102,
        name: 'Incline Barbell Bench Press',
        reps: 6,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 11
      }, {
        id: 103,
        name: 'Power clean and press',
        reps: 4,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 12
      }, {
        id: 104,
        name: 'Power clean and press',
        reps: 4,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 13
      }, {
        id: 105,
        name: 'Power clean and press',
        reps: 4,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 14
      }, {
        id: 106,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 15
      }, {
        id: 107,
        name: 'Deadlifts',
        reps: 6,
        sets: 1,
        weight: 220,
        tempo: '101',
        rest: 60,
        workoutOrder: 16
      }, {
        id: 108,
        name: 'Deadlifts',
        reps: 6,
        sets: 1,
        weight: 220,
        tempo: '101',
        rest: 60,
        workoutOrder: 17
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 20,
    date: '2017-06-17',
    notes: '',
    exercises: [
      {
        id: 76,
        name: 'Bench Press',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 0,
        workoutOrder: 1,
        superSetIndex: 1
      }, {
        id: 77,
        name: 'Bent Over Barbell Rows',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 2,
        superSetIndex: 2
      }, {
        id: 78,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 3,
        superSetIndex: 1
      }, {
        id: 79,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 4,
        superSetIndex: 2
      }, {
        id: 80,
        name: 'Bench Press',
        reps: 6,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 5,
        superSetIndex: 1
      }, {
        id: 81,
        name: 'Bent Over Barbell Rows',
        reps: 6,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 6,
        superSetIndex: 2
      }, {
        id: 82,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 8,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 83,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 8,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 84,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 8,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 85,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 86,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 11
      }, {
        id: 87,
        name: 'Squats',
        reps: 6,
        sets: 1,
        weight: 176,
        tempo: '101',
        rest: 60,
        workoutOrder: 12
      }, {
        id: 88,
        name: 'Squats',
        reps: 3,
        sets: 1,
        weight: 220,
        tempo: '101',
        rest: 0,
        workoutOrder: 13,
        superSetIndex: 1
      }, {
        id: 89,
        name: 'Squats',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 14,
        superSetIndex: 2
      }, {
        id: 90,
        name: 'Single leg static barbell lunges',
        reps: 6,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 15
      }, {
        id: 91,
        name: 'Single leg static barbell lunges',
        reps: 6,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 16
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 19,
    date: '2017-06-11',
    notes: 'light workout',
    exercises: [
      {
        id: 61,
        name: 'Bench Press',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 1
      }, {
        id: 62,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 2
      }, {
        id: 63,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 3
      }, {
        id: 64,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 4
      }, {
        id: 65,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 5
      }, {
        id: 66,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 6
      }, {
        id: 67,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 68,
        name: 'Power cleans',
        reps: 5,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 69,
        name: 'Power cleans',
        reps: 5,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 70,
        name: 'Power cleans',
        reps: 5,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 71,
        name: 'Farmer\'s walk with dumbells',
        reps: 10,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 11
      }, {
        id: 72,
        name: 'Farmer\'s walk with dumbells',
        reps: 10,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 12
      }, {
        id: 73,
        name: 'Seated Cable Rows',
        reps: 8,
        sets: 1,
        weight: 154,
        tempo: '101',
        rest: 60,
        workoutOrder: 13
      }, {
        id: 74,
        name: 'Seated Cable Rows',
        reps: 8,
        sets: 1,
        weight: 154,
        tempo: '101',
        rest: 60,
        workoutOrder: 14
      }, {
        id: 75,
        name: 'Seated Cable Rows',
        reps: 8,
        sets: 1,
        weight: 154,
        tempo: '101',
        rest: 60,
        workoutOrder: 15
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 18,
    date: '2017-06-08',
    notes: '',
    exercises: [
      {
        id: 43,
        name: 'Bench Press',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 0,
        workoutOrder: 1,
        superSetIndex: 1
      }, {
        id: 44,
        name: 'Bent Over Barbell Rows',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 2,
        superSetIndex: 2
      }, {
        id: 45,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 3,
        superSetIndex: 1
      }, {
        id: 46,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 4,
        superSetIndex: 2
      }, {
        id: 47,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 5,
        superSetIndex: 1
      }, {
        id: 48,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 6,
        superSetIndex: 2
      }, {
        id: 49,
        name: 'Incline Barbell Bench Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '303',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 50,
        name: 'Incline Barbell Bench Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '303',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 51,
        name: 'Incline Barbell Bench Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '303',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 52,
        name: 'Seated Military Shoulder Press',
        reps: 6,
        sets: 1,
        weight: 26,
        tempo: '101',
        rest: 0,
        workoutOrder: 10,
        superSetIndex: 1
      }, {
        id: 53,
        name: 'Push-Ups',
        reps: 6,
        sets: 1,
        weight: null,
        tempo: null,
        rest: 60,
        workoutOrder: 11,
        superSetIndex: 2
      }, {
        id: 54,
        name: 'Seated Military Shoulder Press',
        reps: 6,
        sets: 1,
        weight: 26,
        tempo: '101',
        rest: 0,
        workoutOrder: 12,
        superSetIndex: 1
      }, {
        id: 55,
        name: 'Push-Ups',
        reps: 6,
        sets: 1,
        weight: null,
        tempo: null,
        rest: 60,
        workoutOrder: 13,
        superSetIndex: 2
      }, {
        id: 56,
        name: 'Bent Over Dumbbell Rows',
        reps: 8,
        sets: 1,
        weight: 52,
        tempo: '101',
        rest: 60,
        workoutOrder: 14
      }, {
        id: 57,
        name: 'Bent Over Dumbbell Rows',
        reps: 8,
        sets: 1,
        weight: 52,
        tempo: '101',
        rest: 60,
        workoutOrder: 15
      }, {
        id: 58,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 16
      }, {
        id: 59,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 17
      }, {
        id: 60,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 176,
        tempo: '101',
        rest: 60,
        workoutOrder: 18
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 29,
    date: '2017-06-04',
    notes: '',
    exercises: [
      {
        id: 220,
        name: 'Bench Press',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 0,
        workoutOrder: 1,
        superSetIndex: 1
      }, {
        id: 221,
        name: 'Bent Over Barbell Rows',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 2,
        superSetIndex: 2
      }, {
        id: 222,
        name: 'Bench Press',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 3,
        superSetIndex: 1
      }, {
        id: 223,
        name: 'Bent Over Barbell Rows',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 4,
        superSetIndex: 2
      }, {
        id: 224,
        name: 'Bench Press',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 5,
        superSetIndex: 1
      }, {
        id: 225,
        name: 'Bent Over Barbell Rows',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 6,
        superSetIndex: 2
      }, {
        id: 226,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 227,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 228,
        name: 'Power cleans',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 229,
        name: 'Power cleans',
        reps: 5,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 230,
        name: 'Power clean and press',
        reps: 4,
        sets: 1,
        weight: 88,
        tempo: '131',
        rest: 60,
        workoutOrder: 11
      }, {
        id: 231,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 12
      }, {
        id: 232,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 13
      }, {
        id: 233,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 14
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 28,
    date: '2017-05-24',
    notes: '',
    exercises: [
      {
        id: 198,
        name: 'Bench Press',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 1
      }, {
        id: 199,
        name: 'Bench Press',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 2
      }, {
        id: 200,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 3
      }, {
        id: 201,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 4
      }, {
        id: 202,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 5
      }, {
        id: 203,
        name: 'Bent Over Barbell Rows',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 6
      }, {
        id: 204,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 205,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 206,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 207,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 208,
        name: 'Incline Barbell Bench Press',
        reps: 4,
        sets: 1,
        weight: 66,
        tempo: '303',
        rest: 60,
        workoutOrder: 11
      }, {
        id: 209,
        name: 'Incline Barbell Bench Press',
        reps: 4,
        sets: 1,
        weight: 66,
        tempo: '303',
        rest: 60,
        workoutOrder: 12
      }, {
        id: 210,
        name: 'Incline Barbell Bench Press',
        reps: 4,
        sets: 1,
        weight: 66,
        tempo: '303',
        rest: 60,
        workoutOrder: 13
      }, {
        id: 211,
        name: 'Bent Over Dumbbell Rows',
        reps: 4,
        sets: 1,
        weight: 44,
        tempo: '101',
        rest: 60,
        workoutOrder: 14
      }, {
        id: 212,
        name: 'Bent Over Dumbbell Rows',
        reps: 4,
        sets: 1,
        weight: 44,
        tempo: '101',
        rest: 60,
        workoutOrder: 15
      }, {
        id: 213,
        name: 'Bent Over Dumbbell Rows',
        reps: 4,
        sets: 1,
        weight: 44,
        tempo: '101',
        rest: 60,
        workoutOrder: 16
      }, {
        id: 214,
        name: 'Seated Overhead Dumbbell Press',
        reps: 8,
        sets: 1,
        weight: 22,
        tempo: '101',
        rest: 60,
        workoutOrder: 17
      }, {
        id: 215,
        name: 'Seated Overhead Dumbbell Press',
        reps: 3,
        sets: 1,
        weight: 35,
        tempo: '101',
        rest: 60,
        workoutOrder: 18
      }, {
        id: 216,
        name: 'Seated Overhead Dumbbell Press',
        reps: 3,
        sets: 1,
        weight: 35,
        tempo: '101',
        rest: 60,
        workoutOrder: 19
      }, {
        id: 217,
        name: 'Power clean and press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 20
      }, {
        id: 218,
        name: 'Power clean and press',
        reps: 5,
        sets: 1,
        weight: 88,
        tempo: '131',
        rest: 60,
        workoutOrder: 21
      }, {
        id: 219,
        name: 'Power clean and press',
        reps: 5,
        sets: 1,
        weight: 88,
        tempo: '131',
        rest: 60,
        workoutOrder: 22
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 27,
    date: '2017-05-07',
    notes: '',
    exercises: [
      {
        id: 180,
        name: 'Bench Press',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 0,
        workoutOrder: 1,
        superSetIndex: 1
      }, {
        id: 181,
        name: 'Bent Over Barbell Rows',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 2,
        superSetIndex: 2
      }, {
        id: 182,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 3,
        superSetIndex: 1
      }, {
        id: 183,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 4,
        superSetIndex: 2
      }, {
        id: 184,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 5,
        superSetIndex: 1
      }, {
        id: 185,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 6,
        superSetIndex: 2
      }, {
        id: 186,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 187,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 188,
        name: 'Power cleans',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 189,
        name: 'Power cleans',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 190,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 11
      }, {
        id: 191,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 12
      }, {
        id: 192,
        name: 'Squats',
        reps: 6,
        sets: 1,
        weight: 176,
        tempo: '101',
        rest: 60,
        workoutOrder: 13
      }, {
        id: 193,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 14
      }, {
        id: 194,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 15
      }, {
        id: 195,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 16
      }, {
        id: 196,
        name: 'Pull-Ups',
        reps: 6,
        sets: 1,
        weight: null,
        tempo: '101',
        rest: 60,
        workoutOrder: 17
      }, {
        id: 197,
        name: 'Pull-Ups',
        reps: 6,
        sets: 1,
        weight: null,
        tempo: '101',
        rest: 60,
        workoutOrder: 18
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 26,
    date: '2017-05-05',
    notes: '',
    exercises: [
      {
        id: 165,
        name: 'Bench Press',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 0,
        workoutOrder: 1,
        superSetIndex: 1
      }, {
        id: 166,
        name: 'Bent Over Barbell Rows',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 2,
        superSetIndex: 2
      }, {
        id: 167,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 3,
        superSetIndex: 1
      }, {
        id: 168,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 4,
        superSetIndex: 2
      }, {
        id: 169,
        name: 'Bench Press',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 5,
        superSetIndex: 1
      }, {
        id: 170,
        name: 'Bent Over Barbell Rows',
        reps: 5,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 6,
        superSetIndex: 2
      }, {
        id: 171,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 172,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 173,
        name: 'Power cleans',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 174,
        name: 'Power cleans',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 175,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 11
      }, {
        id: 176,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 12
      }, {
        id: 177,
        name: 'Squats',
        reps: 4,
        sets: 1,
        weight: 176,
        tempo: '101',
        rest: 60,
        workoutOrder: 13
      }, {
        id: 178,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 14
      }, {
        id: 179,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 15
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 25,
    date: '2017-04-30',
    notes: '',
    exercises: [
      {
        id: 152,
        name: 'Bench Press',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 0,
        workoutOrder: 1,
        superSetIndex: 1
      }, {
        id: 153,
        name: 'Bent Over Barbell Rows',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 2,
        superSetIndex: 2
      }, {
        id: 154,
        name: 'Bench Press',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 3,
        superSetIndex: 1
      }, {
        id: 155,
        name: 'Bent Over Barbell Rows',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 4,
        superSetIndex: 2
      }, {
        id: 156,
        name: 'Bench Press',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 5,
        superSetIndex: 1
      }, {
        id: 157,
        name: 'Bent Over Barbell Rows',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 6,
        superSetIndex: 2
      }, {
        id: 158,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 159,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 160,
        name: 'Squats',
        reps: 6,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 161,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 162,
        name: 'Power cleans',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 11
      }, {
        id: 163,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 12
      }, {
        id: 164,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 13
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 24,
    date: '2017-04-08',
    notes: '',
    exercises: [
      {
        id: 140,
        name: 'Bench Press',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 0,
        workoutOrder: 1,
        superSetIndex: 1
      }, {
        id: 141,
        name: 'Bent Over Barbell Rows',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 2,
        superSetIndex: 2
      }, {
        id: 142,
        name: 'Bench Press',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 3,
        superSetIndex: 1
      }, {
        id: 143,
        name: 'Bent Over Barbell Rows',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 4,
        superSetIndex: 2
      }, {
        id: 144,
        name: 'Bench Press',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 5,
        superSetIndex: 1
      }, {
        id: 145,
        name: 'Bent Over Barbell Rows',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 6,
        superSetIndex: 2
      }, {
        id: 146,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 147,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 148,
        name: 'Squats',
        reps: 6,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 149,
        name: 'Squats',
        reps: 6,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 150,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 11
      }, {
        id: 151,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 12
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 23,
    date: '2017-04-06',
    notes: 'Starting at Basefit, Sankt Johann, Basel',
    exercises: [
      {
        id: 127,
        name: 'Bench Press',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 0,
        workoutOrder: 1,
        superSetIndex: 1
      }, {
        id: 128,
        name: 'Bent Over Barbell Rows',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 2,
        superSetIndex: 2
      }, {
        id: 129,
        name: 'Bench Press',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 0,
        workoutOrder: 3,
        superSetIndex: 1
      }, {
        id: 130,
        name: 'Bent Over Barbell Rows',
        reps: 4,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 4,
        superSetIndex: 2
      }, {
        id: 131,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 5
      }, {
        id: 132,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 66,
        tempo: '101',
        rest: 60,
        workoutOrder: 6
      }, {
        id: 133,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 88,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 134,
        name: 'Squats',
        reps: 5,
        sets: 1,
        weight: 154,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 135,
        name: 'Squats',
        reps: 5,
        sets: 1,
        weight: 176,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 136,
        name: 'Squats',
        reps: 5,
        sets: 1,
        weight: 176,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 137,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 132,
        tempo: '101',
        rest: 60,
        workoutOrder: 11
      }, {
        id: 138,
        name: 'Pull-Ups',
        reps: 5,
        sets: 1,
        weight: null,
        tempo: '101',
        rest: 60,
        workoutOrder: 12
      }, {
        id: 139,
        name: 'Pull-Ups',
        reps: 5,
        sets: 1,
        weight: null,
        tempo: '101',
        rest: 60,
        workoutOrder: 13
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 81,
    date: '2008-10-02',
    notes: '',
    exercises: [
      {
        id: 333,
        name: 'Pull-Ups',
        reps: 7,
        sets: 1,
        weight: null,
        tempo: '101',
        rest: 0,
        workoutOrder: 1,
        superSetIndex: 1
      }, {
        id: 334,
        name: 'Seated Cable Rows',
        reps: 7,
        sets: 1,
        weight: 75,
        tempo: '101',
        rest: 60,
        workoutOrder: 2,
        superSetIndex: 2
      }, {
        id: 335,
        name: 'Pull-Ups',
        reps: 7,
        sets: 1,
        weight: null,
        tempo: '101',
        rest: 0,
        workoutOrder: 3,
        superSetIndex: 1
      }, {
        id: 336,
        name: 'Seated Cable Rows',
        reps: 7,
        sets: 1,
        weight: 75,
        tempo: '101',
        rest: 60,
        workoutOrder: 4,
        superSetIndex: 2
      }, {
        id: 337,
        name: 'Pull-Ups',
        reps: 7,
        sets: 1,
        weight: null,
        tempo: '101',
        rest: 0,
        workoutOrder: 5,
        superSetIndex: 1
      }, {
        id: 338,
        name: 'Seated Cable Rows',
        reps: 7,
        sets: 1,
        weight: 75,
        tempo: '101',
        rest: 60,
        workoutOrder: 6,
        superSetIndex: 2
      }, {
        id: 339,
        name: 'Seated Cable Rows (reverse grip)',
        reps: 5,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 340,
        name: 'Seated Cable Rows (reverse grip)',
        reps: 5,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 341,
        name: 'Seated Cable Rows (reverse grip)',
        reps: 5,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 342,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 343,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 225,
        tempo: '101',
        rest: 60,
        workoutOrder: 11
      }, {
        id: 344,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 225,
        tempo: '101',
        rest: 60,
        workoutOrder: 12
      }, {
        id: 345,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 225,
        tempo: '101',
        rest: 60,
        workoutOrder: 13
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 80,
    date: '2008-09-29',
    notes: '',
    exercises: [
      {
        id: 295,
        name: 'Bench Press',
        reps: 6,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 1
      }, {
        id: 296,
        name: 'Bench Press',
        reps: 6,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 2
      }, {
        id: 297,
        name: 'Bench Press',
        reps: 6,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 3
      }, {
        id: 298,
        name: 'Bench Press',
        reps: 6,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 4
      }, {
        id: 299,
        name: 'Bench Press',
        reps: 6,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 5
      }, {
        id: 300,
        name: 'Flat Dumbbell Flyes',
        reps: 6,
        sets: 1,
        weight: 35,
        tempo: '101',
        rest: 0,
        workoutOrder: 6,
        superSetIndex: 1
      }, {
        id: 301,
        name: 'Push-Ups',
        reps: 6,
        sets: 1,
        weight: null,
        tempo: '101',
        rest: 60,
        workoutOrder: 7,
        superSetIndex: 2
      }, {
        id: 302,
        name: 'Flat Dumbbell Flyes',
        reps: 6,
        sets: 1,
        weight: 35,
        tempo: '101',
        rest: 0,
        workoutOrder: 8,
        superSetIndex: 1
      }, {
        id: 303,
        name: 'Push-Ups',
        reps: 6,
        sets: 1,
        weight: null,
        tempo: '101',
        rest: 60,
        workoutOrder: 9,
        superSetIndex: 2
      }, {
        id: 304,
        name: 'Flat Dumbbell Flyes',
        reps: 6,
        sets: 1,
        weight: 35,
        tempo: '101',
        rest: 0,
        workoutOrder: 10,
        superSetIndex: 1
      }, {
        id: 305,
        name: 'Push-Ups',
        reps: 6,
        sets: 1,
        weight: null,
        tempo: '101',
        rest: 60,
        workoutOrder: 11,
        superSetIndex: 2
      }, {
        id: 306,
        name: 'Deadlifts',
        reps: 6,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 12
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 79,
    date: '2008-09-26',
    notes: '',
    exercises: [
      {
        id: 278,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 7,
        sets: 1,
        weight: 95,
        tempo: '101',
        rest: 60,
        workoutOrder: 1
      }, {
        id: 279,
        name: 'Power cleans',
        reps: 3,
        sets: 1,
        weight: 115,
        tempo: '101',
        rest: 60,
        workoutOrder: 2
      }, {
        id: 280,
        name: 'Power cleans',
        reps: 3,
        sets: 1,
        weight: 115,
        tempo: '101',
        rest: 60,
        workoutOrder: 3
      }, {
        id: 281,
        name: 'Power cleans',
        reps: 3,
        sets: 1,
        weight: 115,
        tempo: '101',
        rest: 60,
        workoutOrder: 4
      }, {
        id: 282,
        name: 'Power cleans',
        reps: 3,
        sets: 1,
        weight: 115,
        tempo: '101',
        rest: 60,
        workoutOrder: 5
      }, {
        id: 283,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 7,
        sets: 1,
        weight: 95,
        tempo: '101',
        rest: 60,
        workoutOrder: 6
      }, {
        id: 284,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 7,
        sets: 1,
        weight: 95,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 285,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 5,
        sets: 1,
        weight: 95,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 286,
        name: 'Seated Overhead Dumbbell Press',
        reps: 7,
        sets: 1,
        weight: 30,
        tempo: '101',
        rest: 0,
        workoutOrder: 9,
        superSetIndex: 1
      }, {
        id: 287,
        name: 'Dumbbell Shrugs',
        reps: 7,
        sets: 1,
        weight: 100,
        tempo: '101',
        rest: 60,
        workoutOrder: 10,
        superSetIndex: 2
      }, {
        id: 288,
        name: 'Seated Overhead Dumbbell Press',
        reps: 7,
        sets: 1,
        weight: 30,
        tempo: '101',
        rest: 0,
        workoutOrder: 11,
        superSetIndex: 1
      }, {
        id: 289,
        name: 'Dumbbell Shrugs',
        reps: 7,
        sets: 1,
        weight: 100,
        tempo: '101',
        rest: 60,
        workoutOrder: 12,
        superSetIndex: 2
      }, {
        id: 290,
        name: 'Seated Overhead Dumbbell Press',
        reps: 7,
        sets: 1,
        weight: 30,
        tempo: '101',
        rest: 0,
        workoutOrder: 13,
        superSetIndex: 1
      }, {
        id: 291,
        name: 'Dumbbell Shrugs',
        reps: 7,
        sets: 1,
        weight: 100,
        tempo: '101',
        rest: 60,
        workoutOrder: 14,
        superSetIndex: 2
      }, {
        id: 292,
        name: 'Leg Press',
        reps: 10,
        sets: 1,
        weight: 180,
        tempo: '101',
        rest: 60,
        workoutOrder: 15
      }, {
        id: 293,
        name: 'Leg Press',
        reps: 8,
        sets: 1,
        weight: 270,
        tempo: '101',
        rest: 60,
        workoutOrder: 16
      }, {
        id: 294,
        name: 'Leg Press',
        reps: 8,
        sets: 1,
        weight: 270,
        tempo: '101',
        rest: 60,
        workoutOrder: 17
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 39,
    date: '2008-09-23',
    notes: '',
    exercises: [
      {
        id: 264,
        name: 'Decline Barbell Bench Press',
        reps: 8,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 1
      }, {
        id: 265,
        name: 'Decline Barbell Bench Press',
        reps: 8,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 2
      }, {
        id: 266,
        name: 'Decline Barbell Bench Press',
        reps: 5,
        sets: 1,
        weight: 185,
        tempo: '101',
        rest: 60,
        workoutOrder: 3
      }, {
        id: 267,
        name: 'Decline Barbell Bench Press',
        reps: 8,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 4
      }, {
        id: 268,
        name: 'Decline Dumbbell Flyes',
        reps: 6,
        sets: 1,
        weight: 35,
        tempo: '101',
        rest: 60,
        workoutOrder: 5
      }, {
        id: 269,
        name: 'Decline Dumbbell Flyes',
        reps: 6,
        sets: 1,
        weight: 35,
        tempo: '101',
        rest: 60,
        workoutOrder: 6
      }, {
        id: 270,
        name: 'Decline Dumbbell Flyes',
        reps: 6,
        sets: 1,
        weight: 35,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 271,
        name: 'Bent Over Barbell Rows',
        reps: 7,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 272,
        name: 'Bent Over Barbell Rows',
        reps: 7,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 273,
        name: 'Bent Over Barbell Rows',
        reps: 7,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 274,
        name: 'Push-Ups',
        reps: 7,
        sets: 1,
        weight: null,
        tempo: '101',
        rest: 60,
        workoutOrder: 11
      }, {
        id: 275,
        name: 'Push-Ups',
        reps: 7,
        sets: 1,
        weight: null,
        tempo: '101',
        rest: 60,
        workoutOrder: 12
      }, {
        id: 276,
        name: 'Push-Ups',
        reps: 7,
        sets: 1,
        weight: null,
        tempo: '101',
        rest: 60,
        workoutOrder: 13
      }, {
        id: 277,
        name: 'Pull-Ups',
        reps: 10,
        sets: 1,
        weight: null,
        tempo: '101',
        rest: 60,
        workoutOrder: 14
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 38,
    date: '2008-09-19',
    notes: '',
    exercises: [
      {
        id: 251,
        name: 'Power clean and press',
        reps: 7,
        sets: 1,
        weight: 95,
        tempo: '101',
        rest: 60,
        workoutOrder: 1
      }, {
        id: 252,
        name: 'Power clean and press',
        reps: 7,
        sets: 1,
        weight: 95,
        tempo: '101',
        rest: 60,
        workoutOrder: 2
      }, {
        id: 253,
        name: 'Power clean and press',
        reps: 7,
        sets: 1,
        weight: 95,
        tempo: '101',
        rest: 60,
        workoutOrder: 3
      }, {
        id: 254,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 6,
        sets: 1,
        weight: 95,
        tempo: '101',
        rest: 60,
        workoutOrder: 4
      }, {
        id: 255,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 6,
        sets: 1,
        weight: 95,
        tempo: '101',
        rest: 60,
        workoutOrder: 5
      }, {
        id: 256,
        name: 'Standing Overhead Barbell Shoulder Press',
        reps: 6,
        sets: 1,
        weight: 95,
        tempo: '101',
        rest: 60,
        workoutOrder: 6
      }, {
        id: 257,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 258,
        name: 'Deadlifts',
        reps: 6,
        sets: 1,
        weight: 225,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 259,
        name: 'Deadlifts',
        reps: 6,
        sets: 1,
        weight: 225,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 260,
        name: 'Deadlifts',
        reps: 6,
        sets: 1,
        weight: 225,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 261,
        name: 'Dumbbell Preacher Curls',
        reps: 7,
        sets: 1,
        weight: 25,
        tempo: '101',
        rest: 60,
        workoutOrder: 11
      }, {
        id: 262,
        name: 'Dumbbell Preacher Curls',
        reps: 7,
        sets: 1,
        weight: 25,
        tempo: '101',
        rest: 60,
        workoutOrder: 12
      }, {
        id: 263,
        name: 'Dumbbell Preacher Curls',
        reps: 7,
        sets: 1,
        weight: 25,
        tempo: '101',
        rest: 60,
        workoutOrder: 13
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 37,
    date: '2008-09-17',
    notes: '',
    exercises: [
      {
        id: 240,
        name: 'Bench Press',
        reps: 6,
        sets: 1,
        weight: 95,
        tempo: '101',
        rest: 60,
        workoutOrder: 1
      }, {
        id: 241,
        name: 'Bench Press',
        reps: 8,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 2
      }, {
        id: 242,
        name: 'Bench Press',
        reps: 8,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 3
      }, {
        id: 243,
        name: 'Bent Over Barbell Rows',
        reps: 6,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 4
      }, {
        id: 244,
        name: 'Bent Over Barbell Rows',
        reps: 6,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 5
      }, {
        id: 245,
        name: 'Seated Overhead Dumbbell Press',
        reps: 6,
        sets: 1,
        weight: 40,
        tempo: '101',
        rest: 60,
        workoutOrder: 6
      }, {
        id: 246,
        name: 'Seated Overhead Dumbbell Press',
        reps: 6,
        sets: 1,
        weight: 40,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 247,
        name: 'Seated Overhead Dumbbell Press',
        reps: 6,
        sets: 1,
        weight: 40,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }, {
        id: 248,
        name: 'Squats',
        reps: 8,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 9
      }, {
        id: 249,
        name: 'Squats',
        reps: 6,
        sets: 1,
        weight: 225,
        tempo: '101',
        rest: 60,
        workoutOrder: 10
      }, {
        id: 250,
        name: 'Squats',
        reps: 6,
        sets: 1,
        weight: 225,
        tempo: '101',
        rest: 60,
        workoutOrder: 11
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 82,
    date: '2008-08-21',
    notes: '',
    exercises: [
      {
        id: 354,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 1
      }, {
        id: 355,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 225,
        tempo: '101',
        rest: 60,
        workoutOrder: 2
      }, {
        id: 356,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 225,
        tempo: '101',
        rest: 60,
        workoutOrder: 3
      }, {
        id: 357,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 225,
        tempo: '101',
        rest: 60,
        workoutOrder: 4
      }, {
        id: 358,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 225,
        tempo: '101',
        rest: 60,
        workoutOrder: 5
      }, {
        id: 359,
        name: 'Deadlifts',
        reps: 8,
        sets: 1,
        weight: 225,
        tempo: '101',
        rest: 60,
        workoutOrder: 6
      }, {
        id: 360,
        name: 'Floorwipers',
        reps: 16,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 7
      }, {
        id: 361,
        name: 'Floorwipers',
        reps: 16,
        sets: 1,
        weight: 135,
        tempo: '101',
        rest: 60,
        workoutOrder: 8
      }
    ]
  }, {
    userId: '4054a73232db7de8',
    id: 78,
    date: '2008-05-02',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 77,
    date: '2008-04-30',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 76,
    date: '2008-04-28',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 75,
    date: '2008-04-26',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 74,
    date: '2008-04-23',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 73,
    date: '2008-04-22',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 72,
    date: '2008-04-18',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 71,
    date: '2008-04-16',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 70,
    date: '2008-04-11',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 69,
    date: '2008-04-09',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 68,
    date: '2008-04-04',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 67,
    date: '2008-04-02',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 66,
    date: '2008-03-28',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 65,
    date: '2008-03-26',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 64,
    date: '2008-03-19',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 63,
    date: '2008-03-14',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 62,
    date: '2008-03-12',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 61,
    date: '2008-03-07',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 60,
    date: '2008-03-05',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 59,
    date: '2008-02-22',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 58,
    date: '2008-02-20',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 57,
    date: '2008-02-19',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 56,
    date: '2008-02-15',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 55,
    date: '2008-02-13',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 54,
    date: '2008-02-12',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 53,
    date: '2008-02-08',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 52,
    date: '2008-02-06',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 51,
    date: '2008-02-01',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 50,
    date: '2008-01-30',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 49,
    date: '2008-01-25',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 48,
    date: '2008-01-23',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 47,
    date: '2008-01-20',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 46,
    date: '2008-01-18',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 45,
    date: '2008-01-16',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 44,
    date: '2008-01-15',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 43,
    date: '2008-01-11',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 42,
    date: '2008-01-08',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 41,
    date: '2008-01-05',
    notes: '',
    exercises: []
  }, {
    userId: '4054a73232db7de8',
    id: 40,
    date: '2008-01-03',
    notes: '',
    exercises: []
  }
];
